### PR TITLE
added seeding

### PR DESCRIPTION
**Pull request by Dorismandu**
Hey hey, I added the seeding. 
Can you let me know if it looks ok for you? 

I add 3 pics per dog, using cloudinary ( found in our lecture how to use cloudinary for seeding :) ) 

12 dogs in total

### CODE REVIEW

**Comment by Francisco-Webdeveloper** [comment]
Can you send a screenshot of how it looks? Thanks :)

**Comment by Dorismandu** [comment]
there is no proper index view for dogs for now, therefore there is not much to see on the website.
But I can show you one instance of the seeded dog table:

<Dog:0x00007f6a78e47340
 id: 22,
 name: "Casey",
 breed: "Eskimo",
 age: 3,
 description:
  "Looking for someone who could spend time with my dog a few times a week, as I work late and don't want to leave him alone the full day. I could bring him to your place, or you can come dog-sitting in my flat for a few hours. He is very calm, but enjoy playing now and then.",
 user_id: 1,
 created_at: Wed, 28 Apr 2021 15:12:49 UTC +00:00,
 updated_at: Wed, 28 Apr 2021 15:12:49 UTC +00:00>

+ 3 pics. (I checked in the console and they seem correctly added)

1 thing not optimal: As the pics are chosen randomly from a dog collection on Unsplash, they are all dog pics, but 1 dog is likely to have 3 pics showing 3 very different dogs 🙂
What we can do is maybe use this system for now, and see later if there is a way to improve the picture seeding


________________________________
De : Francisco Santos ***@***.***>
Envoyé : mercredi 28 avril 2021 17:44
À : Dorismandu/dogbnb ***@***.***>
Cc : Dorothée Wallois ***@***.***>; Author ***@***.***>
Objet : Re: [Dorismandu/dogbnb] added seeding (#14)


Can you send a screenshot of how it looks? Thanks :)

**Comment by Francisco-Webdeveloper** [comment]
You are right, of course it's not possible without a view :)
It looks great! thanks!

**Comment by BomTenner** [comment]
should we set a limit on how long and short the description for the dog can be? So that when we display the information on the show page we will have a somewhat uniform length for the description. I think it makes designing the page easier

**Comment by BomTenner** [comment]
And I think we also need to add a column with "address" for the dog table. But like the pictures thats something we can add later

**Comment by Dorismandu** [comment]
true, the address is quite important. It should be added to the dog model.
I will add it + add the address to the seed.

I think for the description length limit, we can wait to have the show page designed, that way we will know what would be the optimal length.


________________________________
De : Tom Benner ***@***.***>
Envoyé : jeudi 29 avril 2021 10:37
À : Dorismandu/dogbnb ***@***.***>
Cc : Dorothée Wallois ***@***.***>; Author ***@***.***>
Objet : Re: [Dorismandu/dogbnb] added seeding (#14)


And I think we also need to add a column with "address" for the dog table. But like the pictures thats something we can add later

**Comment by BomTenner** [comment]
Sounds good! Ah also the description will be displayed on the home page in the card

**Comment by Dorismandu** [comment]
in the cards, if it is too long we can set a char limit in the view to display it like :

"Amazing dog, loves to walk for hours and greet every other dogs he encounters. Very friendly with..."

________________________________
De : Tom Benner ***@***.***>
Envoyé : jeudi 29 avril 2021 10:56
À : Dorismandu/dogbnb ***@***.***>
Cc : Dorothée Wallois ***@***.***>; Author ***@***.***>
Objet : Re: [Dorismandu/dogbnb] added seeding (#14)


Sounds good! Ah also the description will be displayed on the home page in the card

**Comment by Ludumo** [comment]
Fantastic!!

**Comment by Ludumo** [comment]
Hope I didn't Mess things up by merging to master. should i revert the commit? also how do i get access to these pictures so I can display? do i need to .env your cloudinary API key?

**Comment by Dorismandu** [comment]
don't revert yet I will have a look.

Yes you need to add:
***@***.***

to your .env file.
You also need to do rails db:migrate after pulling master

________________________________
De : Ludumo Toni ***@***.***>
Envoyé : jeudi 29 avril 2021 13:25
À : Dorismandu/dogbnb ***@***.***>
Cc : Dorothée Wallois ***@***.***>; Author ***@***.***>
Objet : Re: [Dorismandu/dogbnb] added seeding (#14)


Hope I didn't Mess things up by merging to master. should i revert the commit? also how do i get access to these pictures so I can display? do i need to .env your cloudinary API key?

**Comment by Ludumo** [comment]
***@***.*** supposed to be your key?

**Comment by Dorismandu** [comment]
it must have been automatically hidden by Github. I sent it to you via Slack.

________________________________
De : Ludumo Toni ***@***.***>
Envoyé : jeudi 29 avril 2021 13:37
À : Dorismandu/dogbnb ***@***.***>
Cc : Dorothée Wallois ***@***.***>; Author ***@***.***>
Objet : Re: [Dorismandu/dogbnb] added seeding (#14)


@.*** supposed to be your key?

**Comment by Ludumo** [comment]
Thats some smart s**t right there! Thanks got it 👍

**Pull request merged**
